### ISSUE TITLE
Exception during disconnection

### ISSUE THREAD

**Issue by fphilippe** [dotnet/MQTTnet#1066]
### Just a word, to start
!!! Thank you very much for your excellent job !!!

### Describe the bug
When using MQTTNet with ASP .Net Core 3.1,i sometimes have an exception during disconnection.

### Which project is your bug related to?
- Client

### To Reproduce
1. Using this version of MQTTnet '3.0.13'.
2. Run this code 'see below for Controller class'.
4. See error.

### Expected behavior
The expected behaviour is that the controller doesn't throw any exception. But from times to times (unpredictable), i receive the exception in the next paragraph.

I took a look at the MQTTnet.Client.MqttClient code but wasn't able to figure how DisconnectAsync could directly call itself.

### Additional context
As you can see, i used a method called TimeoutAfter. It is because i'm working on a more general problem : my service hangs, from times to times, but silently. More precisely, it consumes CPU and just do nothing (it doesn't receive messages anymore, for example).

When upgrading from 3.0.10 to 3.0.13, with stricly no changes at my code, i had a good improvement of my problem, with less occurences.

### Additional logging

```batch
System.OperationCanceledException: The operation was canceled.
   at MQTTnet.Adapter.MqttChannelAdapter.SendPacketAsync(MqttBasePacket packet, TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.DisconnectAsync(MqttClientDisconnectOptions options, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.DisconnectAsync(MqttClientDisconnectOptions options, CancellationToken cancellationToken)
   at APIK.Binding.ActilityHub.Controllers.UplinkController.TimeoutAfter(Task task, Int32 millisecondsTimeout, String taskName) in /src/src/APIK.Binding.ActilityHub/Controllers/UplinkController.cs:line 94
   at APIK.Binding.ActilityHub.Controllers.UplinkController.Post() in /src/src/APIK.Binding.ActilityHub/Controllers/UplinkController.cs:line 60
```

### Code example
 
```csharp
namespace Controllers
{
    [ApiController]
    [Route("uplink")]
    public class UplinkController : ControllerBase
    {
        private readonly ILogger<UplinkController> _logger;
        private readonly IMQTTConnectionFactory _mqttConnectionFactory;

        public UplinkController(ILogger<UplinkController> logger, IDbConnectionFactory dbConnectionFactory, IMQTTConnectionFactory mqttConnectionFactory)
        {
            _logger = logger;
            _mqttConnectionFactory = mqttConnectionFactory;
        }

        [HttpPost]
        public async Task<IActionResult> Post()
        {
            try
            {                
                using (var mqttClient = await TimeoutAfter(_mqttConnectionFactory.GetClientASync(), 5000, "_mqttConnectionFactory.GetClientASync()"))
                {
                    var payload = "Hello, world!";
                    
                    var message = new MqttApplicationMessageBuilder()
                        .WithTopic("ActilityHub/Uplink/")
                        .WithPayload(payload)
                        .WithQualityOfServiceLevel(MqttQualityOfServiceLevel.AtLeastOnce)
                        .Build();
                    await TimeoutAfter(mqttClient.PublishAsync(message), 5000, "mqttClient.PublishAsync(message)");

                    message = new MqttApplicationMessageBuilder()
                        .WithTopic("actilityhub/uplink/")
                        .WithPayload(payload)
                        .WithQualityOfServiceLevel(MqttQualityOfServiceLevel.AtLeastOnce)
                        .Build();
                    await TimeoutAfter(mqttClient.PublishAsync(message), 5000, "mqttClient.PublishAsync(message)");

                    await TimeoutAfter(mqttClient.DisconnectAsync(), 5000, "mqttClient.DisconnectAsync");
                }
            }
            catch (Exception ex)
            {
                _logger.LogError("Une erreur de traitement grave a été rencontrée : {exception}", ex.ToString());
            }
            return Ok();
        }

        public async Task<T> TimeoutAfter<T>(Task<T> task, int millisecondsTimeout, string taskName = "undefined task")
        {
            if (task == await Task.WhenAny(task, Task.Delay(millisecondsTimeout)))
            {
                return await task;
            }
            else
            {
                _logger.LogError("Expiration d'un timeout durant le traitement de {task}", taskName);
                throw new TimeoutException("Expiration d'un timeout durant le traitement de " + taskName);
            }
        }

        public async Task TimeoutAfter(Task task, int millisecondsTimeout, string taskName = "undefined task")
        {
            if (task == await Task.WhenAny(task, Task.Delay(millisecondsTimeout)))
            {
                await task;
            }
            else
            {
                _logger.LogError("Expiration d'un timeout durant le traitement de {task}", taskName);
                throw new TimeoutException("Expiration d'un timeout durant le traitement de " + taskName);
            }
        }
    }
}
```

**Comment by chkr1011** [comment]
@fphilippe Please try with latest RC from nuget. We changed some bits in exactly that area.

**Comment by fphilippe** [comment]
Hi @chkr1011,

Thank you very much for your reply. I've put the 3.0.14-rc8 version of your lib in test and as you expected, the function TimeoutAfter has not thrown any more exception. However, i continue to have a strange behaviour regarding to the disconnection behaviour... From time to time, my program hangs without exiting nor throwing any exception. When using dotnet trace, i see a hot trace around MqttTcpChannelDispose, after beeing passed in TryInitiateDisconnect. You'll find, in the following screenshot, the hot trace :

![trace](https://user-images.githubusercontent.com/13876394/107144442-7ca35d00-693b-11eb-860c-9f786b7d7158.png)

I make a link with the previous behaviour i've described in this issue. Perhaps i'm totally wrong, or i make a mistake in using the lib...

Regards,

Fabien

**Comment by chkr1011** [comment]
Please test with version 4 and reopen this ticket if the issue still occurs.
