### ISSUE TITLE
Connection hangs forever when "server" parameter is only a number

### ISSUE THREAD

**Issue by Tum4ik** [dotnet/MQTTnet#1161]
### Describe the bug
When trying to connect to the server using "WithTcpServer" method and specifying the "server" parameter as just a number, the connection process goes forever even without throwing exception.

### Which project is your bug related to?

- Client

### To Reproduce
1. Using this version of MQTTnet '3.0.15'.
2. Run this code:
```csharp
IMqttClient mqttClient = new MqttFactory().CreateMqttClient();
var options = new MqttClientOptionsBuilder()
  .WithProtocolVersion(MqttProtocolVersion.V500)
  .WithClientId("anyId")
  .WithTcpServer("42", 55) // notice here "42" is a simple number, 
                           // however it will work properly with value "42.6" for example
  .WithCredentials("username", "password")
  .WithCleanSession(false)
  .WithCommunicationTimeout(TimeSpan.FromSeconds(5))
  .Build();
try
{
  await mqttClient
    .ConnectAsync(options)
    .ConfigureAwait(false);
}
catch (MqttCommunicationException e)
{
}
```
3. Notice the connection process goes forever.

### Expected behavior
I guess the best behavior here is just to throw an exception.

**Comment by SeppPenner** [comment]
Interesting, I will have a look at this soon. Seems like the IP address validation is broken here...

**Comment by SeppPenner** [comment]
@chkr1011 @JanEggers Should MQTTnet do some checks on the hosts the user provides?

Something like:

```csharp
public bool IsHostnameValid(string hostName)
{
    var isHostName = Regex.Match(hostName, @"^[A-Za-z]+");
	
    if(isHostName)
    {
        return true;
    }
    else
    {
        try
        {
            // From https://github.com/jsakamoto/ipaddressrange maybe?
            _ = IPAddress.Parse(hostName);
            return true;
        }
        catch (Exception ex)
        {
            throw ex;
        }
        finally
        {
            return false;
        }
    }
}
```

**Comment by JanEggers** [comment]
we use the default .net socket to establish a connection. 

https://github.com/chkr1011/MQTTnet/blob/8f1d4e3c22f3226570eec681bccef3a88c4ebd16/Source/MQTTnet/Implementations/MqttTcpChannel.cs#L75

if that fails to throw an exception whith invalid input please file an issue in the dotnet repo.

I think it is counterproductive to fix / workaround the issue here as it may introduce new issues.

**Comment by yyjdelete** [comment]
Unable to reproduce that.

Seems `42` is just handled as `0.0.0.42` on both windows and linux, and it will throw an SocketException `(10051): A socket operation was attempted to an unreachable network.` on windows, and `System.Net.Sockets.SocketException (111): Connection refused` on linux.


```
(windows)>ping 42

Pinging 0.0.0.42 with 32 bytes of data:
PING: transmit failed. General failure.
PING: transmit failed. General failure.
---
(linux)$ ping 42
ping: connect: Invalid argument

// It didn't show ip addr, but (2130706433 = 0x7F000001)
$ ping 2130706433
PING 2130706433 (127.0.0.1) 56(84) bytes of data.
```
win10+net5.0
```
MQTTnet.Exceptions.MqttCommunicationException: Error while connecting with host '42:55'.
 ---> System.Net.Sockets.SocketException (10051): A socket operation was attempted to an unreachable network.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at MQTTnet.Implementations.CrossPlatformSocket.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MQTTnet.Implementations.CrossPlatformSocket.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync(CancellationToken cancellationToken)
   at MQTTnet.Internal.MqttTaskTimeout.WaitAsync(Func`2 action, TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken) 
```
Ubuntu20.04+net5.0
```cs
MQTTnet.Exceptions.MqttCommunicationException: Error while connecting with host '42:55'.
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at MQTTnet.Implementations.CrossPlatformSocket.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MQTTnet.Implementations.CrossPlatformSocket.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync(CancellationToken cancellationToken)
   at MQTTnet.Internal.MqttTaskTimeout.WaitAsync(Func`2 action, TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
```

**Comment by Tum4ik** [comment]
@yyjdelete hm... I use Xamarin.Forms application to connect to my PC. So it seems to be Mono problem.

**Comment by Tum4ik** [comment]
@yyjdelete hm... I use Xamarin.Forms application to connect to my PC. So it seems to be Mono problem.

**Comment by SeppPenner** [comment]
Since this seems to be a mono specific issue, there's not much we can do here...
