### ISSUE TITLE
Will_Message_Send fails with System.ObjectDisposedException due to a data race in MqttChannelAdapter

### ISSUE THREAD

**Issue by elmerjfudd** [dotnet/MQTTnet#1187]
### Describe the bug
`Will_Message_Send` ocasionally fails with `System.ObjectDisposedException` (see callstack below). After some digging it looks like `Dispose()` races with `TryReceivePacketsAsync()` and disposes the underlying `MqttChannelAdapter` object, making `ThrowIfDisposed()` throw the exception.

```bash
Failed Will_Message_Send [1 s]

  Error Message:
   Test method MQTTnet.Tests.Server_Tests.Will_Message_Send threw exception:
System.Exception: Client(s) had 1 errors ($[2021-07-06T19:52:47.6682573Z] [client] [18] [MqttClient] [Error]: Error while receiving packets.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MqttChannelAdapter'.
   at MQTTnet.Internal.Disposable.ThrowIfDisposed() in D:\MQTTNet\Source\MQTTnet\Internal\Disposable.cs:line 13
   at MQTTnet.Adapter.MqttChannelAdapter.<ReceivePacketAsync>d__31.MoveNext() in D:\GitBench\Apps\mqttnet.apr21\Source\MQTTnet\Adapter\MqttChannelAdapter.cs:line 159
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MQTTnet.Client.MqttClient.<TryReceivePacketsAsync>d__52.MoveNext() in D:\GitBench\Apps\mqttnet.apr21\Source\MQTTnet\Client\MqttClient.cs:line 504).
  Stack Trace:
      at MQTTnet.Tests.Mockups.TestEnvironment.ThrowIfLogErrors()
   at MQTTnet.Tests.Mockups.TestEnvironment.Dispose()
   at MQTTnet.Tests.Server_Tests.<Will_Message_Send>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)
```

### Which project is your bug related to?
- Client (channel adapter)

### To Reproduce
We observe the error occasionally in our logs during nightly builds. However, we are able to increase its frequency by inserting a short `Thread.Sleep(1)` in `MqttChannelAdapter::ReceivePacketAsync()` right before the `ThrowIfDispose()` call (https://github.com/chkr1011/MQTTnet/blob/master/Source/MQTTnet/Adapter/MqttChannelAdapter.cs#L155):

```csharp
public async Task<MqttBasePacket> ReceivePacketAsync(CancellationToken cancellationToken)
{
    cancellationToken.ThrowIfCancellationRequested();
#if !NETSTANDARD1_3
    Thread.Sleep(1);  // <--- delaying thread here, might want to increase the value to 10ms or 100ms to trigger the bug
#endif
    ThrowIfDisposed();

    try
    {
        _packetInspectorHandler.BeginReceivePacket();
        ...
```

Delaying the thread makes the bug reproducible almost every time on our machines. However, you might want to increase that to 10ms or 100ms.

**Comment by elmerjfudd** [comment]
This issue still occurs with the most recent commit, i.e., cf2974c
I was wondering if there is any fix currently in the works.

**Comment by chkr1011** [comment]
I tried the Unit Tests 20 times in a row including your proposed change. Every time it works perfectly. Please try with the latest version 4.0 on nuget and reopen this ticket if the error persists.

**Comment by elmerjfudd** [comment]
Confirming that the latest version no longer has the bug. Thank you, @chkr1011!
