### ISSUE TITLE
Manage_Session_MaxParallel_Subscribe fails with System.ObjectDisposedException due to a data race in MqttChannelAdapter

### ISSUE THREAD

**Issue by elmerjfudd** [dotnet/MQTTnet#1188]
### Describe the bug
`Manage_Session_MaxParallel_Subscribe` ocasionally fails with `System.ObjectDisposedException` (see callstack below). After some digging it looks like the underlying `MqttChannelAdapter` gets disposed asyncornously while `SendAndReceiveAsync()` is still in flight. We suspect `MqttChannelAdapter::Dispose()` races with `MqttClient::SendAndReceiveAsync()` (more precisely, with `MqttChannelAdapter::SendPacketAsync()`).

```bash
Failed Manage_Session_MaxParallel_Subscribe [9 s]

  Error Message:
   Test method MQTTnet.Tests.Server_Tests.Manage_Session_MaxParallel_Subscribe threw exception:
System.Exception: Client(s) had 1 errors ($[2021-07-07T18:52:44.7572991Z] [client] [18] [MqttClient] [Error]: Error while receiving packets.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MqttChannelAdapter'.
   at MQTTnet.Internal.Disposable.ThrowIfDisposed() in D:\MQTTNet\Source\MQTTnet\Internal\Disposable.cs:line 13
at MQTTnet.Adapter.MqttChannelAdapter.<SendPacketAsync>d__30.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at MQTTnet.Adapter.MqttChannelAdapter.SendPacketAsync(MqttBasePacket packet, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.SendAsync(MqttBasePacket packet, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.<SendAndReceiveAsync>d__50`1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at MQTTnet.Client.MqttClient.SendAndReceiveAsync[TResponsePacket](MqttBasePacket requestPacket, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.<SubscribeAsync>d__38.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at MQTTnet.Client.MqttClient.SubscribeAsync(MqttClientSubscribeOptions options, CancellationToken cancellationToken)
   at MQTTnet.Tests.Mockups.TestClientWrapper.SubscribeAsync(MqttClientSubscribeOptions options, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClientExtensions.SubscribeAsync(IMqttClient client, MqttClientSubscribeOptions options)
   at MQTTnet.Client.MqttClientExtensions.SubscribeAsync(IMqttClient client, MqttTopicFilter[] topicFilters)
   at MQTTnet.Client.MqttClientExtensions.SubscribeAsync(IMqttClient client, String topic)
   at MQTTnet.Tests.ManagedMqttClient_Tests.<TryConnect_Subscribe>d__13.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at MQTTnet.Tests.Mockups.TestEnvironment.<ConnectClientAsync>d__40.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at MQTTnet.Client.MqttClient.<ConnectAsync>d__34.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at MQTTnet.Client.MqttClient.<AuthenticateAsync>d__43.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at MQTTnet.Client.MqttClient.<SendAndReceiveAsync>d__50`1.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at MQTTnet.PacketDispatcher.MqttPacketAwaiter`1.<WaitOneAsync>d__6.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

### Which project is your bug related to?
- Client (channel adapter)

### To Reproduce
We observe the error occasionally in our logs during nightly builds. The `ObjectDisposedException` seems to be masked by the `try { } catch` block in `SendAndReceiveAsync()` here: https://github.com/chkr1011/MQTTnet/blob/d1c883ebae8837b4657be49b514ac37a7c75eee0/Source/MQTTnet/Client/MqttClient.cs#L419

To increase the frequency of the bug and enhance the error messages we modify `SendAndReceiveAsync()` slightly by inserting a delay right before `await SendAsync()`, explicitly capturing the `ObjectDisposeException` exception, and triggering an assertion:

```csharp
async Task<TResponsePacket> SendAndReceiveAsync<TResponsePacket>(MqttBasePacket requestPacket, CancellationToken cancellationToken) where TResponsePacket : MqttBasePacket
{
            [...]

            using (var packetAwaiter = _packetDispatcher.AddAwaiter<TResponsePacket>(packetIdentifier))
            {
                try
                {
#if !NETSTANDARD1_3
                    Thread.Sleep(10); // <--- delaying thread here, might want to increase the value to trigger the bug (e.g., 100ms)
#endif
                    await SendAsync(requestPacket, cancellationToken).ConfigureAwait(false);
                }
                catch (ObjectDisposedException e) // <--- explicitly capture ObjectDisposedException to highlight the error
                {
                    System.Diagnostics.Debug.Assert(false, e.Message); // <--- trigger an assert in case the ODE is masked by some other exception
                }
                catch (Exception exception)
                {
                    _logger.Warning(exception, "Error when sending request packet ({0}).", requestPacket.GetType().Name);
                    packetAwaiter.Fail(exception);
                }

                [...]
        }
}
```

Delaying the thread makes the bug reproducible almost every time on our machines. However, it might be necessary to increase that value on your machines (e.g.,100ms).

### Note

This bug looks similar to #1146 although ours happens on a Windows machine, failure paths are slightly different, and we have a systematic way to reproduce it. On the other hand, it might also be related to #1187.

**Comment by elmerjfudd** [comment]
This issue still occurs with the most recent commit, i.e., cf2974c
I was wondering if there is any fix currently in the works.

**Comment by chkr1011** [comment]
The build from GitHub actions are running perfectly. Could you please retry with the latest version and let me know if it still fails?

**Comment by chkr1011** [comment]
Please reopen this ticket if the error persists with version 4.

**Comment by elmerjfudd** [comment]
Confirming that the latest version no longer has the bug. Thank you, @chkr1011!
