### ISSUE TITLE
TLS error connecting to Hive

### ISSUE THREAD

**Issue by ridomin** [dotnet/MQTTnet#1329]
Using the [v4 preview1](https://github.com/dotnet/MQTTnet/releases/tag/v4.0.0-preview1)

Trying to connect to hiveMQ 

```cs
var client = new MqttFactory().CreateMqttClient();
        var connAck = await client.ConnectAsync(new MqttClientOptionsBuilder()
            .WithTls()
            .WithTcpServer("xxxxxxxxxxxxxxxxxxxxxxx.s2.eu.hivemq.cloud", 8883)
            .WithCredentials("client1", "xxxxxxxxxxxxxxx")
            .WithClientId("tlsRepro")
            .Build()
        );
```

some machines fail with (same code works fine in other machines and OSes)

```
System.Security.Authentication.AuthenticationException
  HResult=0x80131501
  Message=The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

Runtime Environment:
```
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\
```

**Comment by chkr1011** [comment]
Thank you for reporting issues with the latest preview.

Please try setting the protocol version for TLS to 1.2. The code has changed so that the OS decides which version the default ist. So maybe some OS are requiring TLS 1.3 but the server does not support it.

**Comment by ridomin** [comment]
Tried forcing TLS1.2 and got same results.

I believe this is happening because Hive is using a Let'sEncrypt cert that for some reason some machines are not able to validate, hence the `The remote certificate was rejected`.

If I provide my custom `RemoteCertificateValidationCallback` disabling revocation checks, the connection succeeds.

I also tried with `openssl s_client` and the connection succeeds.

Any clue on how to troubleshoot? I'd like to to get repro code to report to `dotnet/runtime`

**Comment by chkr1011** [comment]
@YerayAlonso The samples are connecting with public broker which are sometimes down or having certificate issues (the one for mqtt.fluux.io is expired since April). I changed the code so that certificate errors are ignored in the samples for now.

@ridomin You can add a certificate validation handler and print the passed certificate information to the console etc. Then you can see the root cause of the issue. If the problem still exists please reopen the ticket.

**Comment by ridomin** [comment]
The root cause was included in the original issue: 

```
The remote certificate was rejected by the provided RemoteCertificateValidationCallback
```

Some machines have issues validating revocation from Let's Encrypt certificates. 
I dont think this is an issue in MQTTNet code, seems like an issue in dotnet with Let's Encrypt certs.

To repro, I'm running this code

```cs
using System.Net.Security;
using System.Net.Sockets;
using System.Security.Cryptography.X509Certificates;

var host = "f8826e3352314ca98102cfbde8aff20e.s2.eu.hivemq.cloud";
var socket = new Socket(SocketType.Stream, ProtocolType.Tcp);
socket.Connect(host, 8883);
var stream = new NetworkStream(socket);
var sslStream = new SslStream(stream);
sslStream.AuthenticateAsClient(host, new X509CertificateCollection(), true);
Console.WriteLine(sslStream.IsAuthenticated);
```

some machines fail with:

```
System.Security.Authentication.AuthenticationException
  HResult=0x80131501
  Message=The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown, OfflineRevocation
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__173`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, Boolean checkCertificateRevocation)

```

@YerayAlonso can you try in other machine and share the details?

**Comment by YerayAlonso** [comment]
Works fine for me with `host = "f8826e3352314ca98102cfbde8aff20e.s2.eu.hivemq.cloud";`.  
But fails for me with `host = "test.mosquitto.org";` with this error:

```
System.Security.Authentication.AuthenticationException
  HResult=0x80131501
  Message=The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown, PartialChain, OfflineRevocation
  Source=System.Net.Security
  StackTrace:
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__173`1.MoveNext()
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, Boolean checkCertificateRevocation)
```

**Comment by ridomin** [comment]
test.mosquitto.org on 8883 requires to validate the chain using https://test.mosquitto.org/ssl/mosquitto.org.crt (as described in https://test.mosquitto.org)

they also offer a let's encrypt endpoint at port 8081 that works for me.
