### ISSUE TITLE
Using Wildcard SSL Cert in Server

### ISSUE THREAD

**Issue by alberk8** [dotnet/MQTTnet#1359]
### Verification

Before opening a bug make sure that the following conditions are met.

1. Performance issues are also appearing in RELEASE mode of your application.
2. An increased memory consumption or high CPU load also happens when your application runs in RELEASE mode AND logging is DISABLED.
3. Client issues with not received messages, connection drops etc. can be reproduced via another client application like "MQTTnetApp" (https://github.com/chkr1011/MQTTnetApp) or similar.
4. The bug also appears in the VERY LATEST version of this library. There is no support for older version (due to limited resources) but pull requests for older versions are welcome.

### Describe the bug
I build a simple MQTT server with an LetsEncrypt WildCard certificate

### Which component is your bug related to?

- Server

### To Reproduce
1. Using this version of MQTTnet '3.1.2'.
2. .NetCore 5 Console Client App
3. See error.
```
MQTTnet.Exceptions.MqttCommunicationException
  HResult=0x80131500
  Message= Received an unexpected EOF or 0 bytes from the transport stream.
  Source=MQTTnet
  StackTrace:
   at MQTTnet.Adapter.MqttChannelAdapter.WrapAndThrowException(Exception exception)
   at MQTTnet.Adapter.MqttChannelAdapter.<ConnectAsync>d__28.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at MQTTnet.Client.MqttClient.<ConnectAsync>d__34.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MQTTnet.Client.MqttClient.<ConnectAsync>d__34.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MqClientTest.Program.<Main>d__0.MoveNext() in D:\MqClientTest\MqClientTest\Program.cs:line 51

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
```
### Expected behavior
Connect to Mqtt Server using WildCard  SSL Certificate

### Additional context / logging
Include debugging or logging information here:

```batch
\\ Put your logging output here.
```
### Code example
Please provide full code examples below where possible to make it easier for the developers to check your issues.

**Ideally a Unit Test (which shows the error) is provided so that the behavior can be reproduced easily.**
 
```csharp
using MQTTnet;
using MQTTnet.Client;
using MQTTnet.Client.Options;

using System;
using System.Text;
using System.Threading;

namespace MqClientTest
{
    class Program
    {
        static async System.Threading.Tasks.Task Main(string[] args)
        {
           

            var options = new MqttClientOptionsBuilder()
                .WithClientId(Guid.NewGuid().ToString())
            
                
                .WithTcpServer((opt) => {
                   
                    opt.Server = "dev.company.com";
                    opt.Port = 8883;
                    opt.TlsOptions = new MqttClientTlsOptions { UseTls = true, 
                        SslProtocol = 
                         System.Security.Authentication.SslProtocols.Tls12 , |
                         System.Security.Authentication.SslProtocols.Tls11 | 
                         System.Security.Authentication.SslProtocols.Tls12 |
                         System.Security.Authentication.SslProtocols.Tls13,
                     AllowUntrustedCertificates = true};
                })
                .Build();

            var mqttClient = new MqttFactory().CreateMqttClient();

           


            // Subcribe
            mqttClient.UseConnectedHandler(async e =>
            {
                wait mqttClient.SubscribeAsync(new MqttTopicFilterBuilder().WithTopic("/Test1").Build());
            });

            mqttClient.UseApplicationMessageReceivedHandler(e =>
            {
                Console.WriteLine(Encoding.UTF8.GetString(e.ApplicationMessage.Payload) + " -> LocalTime: " + DateTime.Now);
            });

            await mqttClient.ConnectAsync(options, CancellationToken.None);
           
            Console.WriteLine("Done");
            Console.ReadKey();
        }
    }
}
```
Server Code
```
using MQTTnet;
using MQTTnet.Server;
using System;
using System.IO;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;

namespace MQTT_SimpleServer
{
    class Program
    {


        static async Task Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            var fullchain = File.ReadAllText("fullchain.pem");
            var priKey = File.ReadAllText("privkey.pem");

            X509Certificate2 cert = X509Certificate2.CreateFromPem(fullchain, priKey);

            var mqttFactory = new MqttFactory();

            // The port for the default endpoint is 1883.
            // The default endpoint is NOT encrypted!
            // Use the builder classes where possible.
            var mqttServerOptions = new MqttServerOptionsBuilder()
                .WithEncryptedEndpoint()
                .WithEncryptionCertificate(cert)
                .WithEncryptedEndpointPort(8883)
                .WithEncryptionSslProtocol(
                  System.Security.Authentication.SslProtocols.Tls11 |
                  System.Security.Authentication.SslProtocols.Tls12 |
                  System.Security.Authentication.SslProtocols.Tls13)
                .Build();

            using (var mqttServer = mqttFactory.CreateMqttServer())
            {
                await mqttServer.StartAsync(mqttServerOptions);

                Console.WriteLine("Press Enter to exit.");
                Console.ReadLine();

                // Stop and dispose the MQTT server if it is no longer needed!
                await mqttServer.StopAsync();
            }
        }
    }
}

```

**Comment by alberk8** [comment]
I have found the problem and the fixed with the code below.  The reported dotnet problem this is never going to be fixed. [ssl credential](https://github.com/dotnet/runtime/issues/45680)

```
 var fullchain = File.ReadAllText("fullchain.pem");
 var priKey = File.ReadAllText("privkey.pem");

X509Certificate2 cert0 = X509Certificate2.CreateFromPem(fullchain, priKey);
509Certificate2 cert = new X509Certificate2(cert0.Export(X509ContentType.Pkcs12)); 

```
