### ISSUE TITLE
MQTTClient.ConnectAsync does not return/throw if broker disconnects, instead times out. Different than 2.8 behavior

### ISSUE THREAD

**Issue by AngelKeeperMN** [dotnet/MQTTnet#1377]
### Describe your question
We have some custom broker authentication mechanisms which if are not met, the broker disconnects the connection. This is an expected outcome. It has to do establishing initial trust using single use data to setup a form of mutual authentication.

When using MQTTNet 2.8.5, when the broker closes the connection because the single use data has already been used, ConnectAsync threw an MqttCommunicationClosedGracefullyException.
2.8.5 Stack trace:

> MQTTnet.Exceptions.MqttCommunicationClosedGracefullyException: Exception of type 'MQTTnet.Exceptions.MqttCommunicationClosedGracefullyException' was thrown.
   at MQTTnet.Serializer.MqttPacketReader.ReadFixedHeaderAsync(IMqttChannel channel, Byte[] fixedHeaderBuffer, Byte[] singleByteBuffer, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReceiveAsync(CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReceivePacketAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ReceivePacketsAsync(CancellationToken cancellationToken)
   at MQTTnet.Internal.TaskExtensions.TimeoutAfterAsync[TResult](Func`2 action, TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.SendAndReceiveAsync[TResponsePacket](MqttBasePacket requestPacket, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.AuthenticateAsync(MqttApplicationMessage willApplicationMessage, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options)
   at Broker.Communication.Activator.BrokerConnectionActivationStartupFilter.ActivateAsync()

In 3.1.1 (and 3.1.2) in this same scenario, we do not get this exception and the ConnectAsync call does not complete until the comm timeout occurs.
So I see from your upgrade guide I should add a DisconnectedHandler, so I did that (and also tried UseDisconnectHanlder(...))

When I call ConnectAsync() the disconnected handler gets called almost immediately because the broker disconnects (which is by design for this use case).

However the ConnectAsync call does not return or throw when I await the result until the connection timeout has occurred, even though the connection has been disconnected. 
I have tried using a CancellationToken and cancelling the ConnectAsync call in my disconnected handler but that does not seem to cancel the action either. 

Any advice on what I should do to get the ConnectAsync call to either fail when it has connected and the broker closes the connection or to cancel the connection attempt in this case?

### Which project is your question related to?

- Client

**Comment by chkr1011** [comment]
Is it possible to create a Unit Test for this situation so that I can reproduce it?

**Comment by AngelKeeperMN** [comment]
I'm not sure I can build a Unit Test as our broker (Apache ArtemisMQ) might be doing something interesting, but I will try. 
In the meantime a little more information after further investigation:

My code is trying various values of the single use data in order to find one which has not been used already (this data is baked into a custom installer which has limited uses, there is a list of them to use, lets say 10 different values).  This is all wrapped up into the password we specify in MqttClientOptionsBuilder.withCredentials()  (Assuming all the single use data has already been used once since this is an "error" scenario")
So the pattern is, build the password with single use data 1, attempt connection. Broker closes the connection. Detect this, then try the next one in the list.  

Some code which demonstrates the issue. (this is inside a loop where we try with different single use data) Verbose logging for this code below:

`
                   
                    var options = new MqttClientOptionsBuilder()
                        .WithClientId(policy.InstanceId + "-ACTIVATION")
                        .WithTcpServer(ActivationConfiguration.BrokerUri.Host, ActivationConfiguration.BrokerUri.Port)
                        .WithCredentials(ActivationConfiguration.BrokerUsername, token)
                        .WithCleanSession()
                        .WithCommunicationTimeout(TimeSpan.FromSeconds(ActivationConfiguration.TimeoutSeconds))
                        .WithTls(new MqttClientOptionsBuilderTlsParameters()
                        {
                            AllowUntrustedCertificates = false,
                            IgnoreCertificateChainErrors = false,
                            IgnoreCertificateRevocationErrors = true,
                            UseTls = true,
                            SslProtocol = System.Security.Authentication.SslProtocols.Tls12
                        }
                        ).Build();
                     Logger.Info("MainThread: Sending Activation Token to Broker to establish trust. BrokerUri: " + ActivationConfiguration.BrokerUri);
                    var cancelTokenSource = new CancellationTokenSource();
                    MqttClient.Value.UseDisconnectedHandler(new MqttClientDisconnectedHandlerDelegate((a) =>
                    {
                        Logger.Error(a.Exception, $"DisconnectHandler: Broker Disconnected. Reason: {a.Reason} Exception: {a.Exception}"); 
                        cancelTokenSource.Cancel();
                        Logger.Info($"DisconnectHandler: ConnectAsync() Task has been requested to cancel: CancelTokenSource.IsCancellationRequested:{cancelTokenSource.IsCancellationRequested}");
                    }));
                    MqttClient.Value.ConnectedHandler = new MqttClientConnectedHandlerDelegate((a) =>
                    {
                        Logger.Info($"ConnectedHandler: Broker Connection established. {a.ConnectResult.ResultCode}");
                    });
                   
                    var connTask = MqttClient.Value.ConnectAsync(options, cancelTokenSource.Token);
                    //Added below to show the task status. The status never changes until we get a timeout exception.
                    int retry = 5;
                    while(retry-- > 0 && !connTask.IsCompleted)
                    {
                        Logger.Info($"MainThread: ConnTask.Status: {connTask.Status} ConnTask.IsCanceled: {connTask.IsCanceled} ConnTask.IsFaulted: {connTask.IsFaulted}");
                        Thread.Sleep(1000);
                    }
                    Logger.Info("MainThread: Awaiting connTask result now");
                    var connectResult = connTask.GetAwaiter().GetResult();

                    Logger.Info("Activation: SUCCESS!");

                    MqttClient.Value.DisconnectAsync().GetAwaiter().GetResult();
`

Log file output. This shows 2 attempts to use already used token, where our broker immediately closes the connection on connection attempt (where with 2.8.5 we would get an exception) and then a third attempt which is successful to show the happy path:
[11:50:25 INF] Attempting to activate
[11:50:26 INF] MainThread: Sending Activation Token to Broker to establish trust. BrokerUri: 
[11:50:26 INF] MqttClient: Verbose Trying to connect with server 'REDACTED' (Timeout=00:02:00).
[11:50:26 INF] MainThread: ConnTask.Status: WaitingForActivation ConnTask.IsCanceled: False ConnTask.IsFaulted: False
[11:50:26 INF] MqttClient: Verbose Connection with server established.
[11:50:26 INF] MqttClient: Verbose Start receiving packets.
[11:50:26 INF] MqttClient: Verbose Disconnecting [Timeout=00:02:00]
[11:50:26 INF] MqttClient: Verbose Disconnected from adapter.
[11:50:26 INF] MqttClient: Info Disconnected.
[11:50:26 INF] MqttClient: Verbose Stopped receiving packets.
[11:50:26 ERR] DisconnectHandler: Broker Disconnected. Reason: NormalDisconnection Exception:
[11:50:26 INF] DisconnectHandler: ConnectAsync() Task has been requested to cancel: CancelTokenSource.IsCancellationRequested:True
[11:50:27 INF] MainThread: ConnTask.Status: WaitingForActivation ConnTask.IsCanceled: False ConnTask.IsFaulted: False
[11:50:28 INF] MainThread: ConnTask.Status: WaitingForActivation ConnTask.IsCanceled: False ConnTask.IsFaulted: False
[11:50:29 INF] MainThread: ConnTask.Status: WaitingForActivation ConnTask.IsCanceled: False ConnTask.IsFaulted: False
[11:50:30 INF] MainThread: ConnTask.Status: WaitingForActivation ConnTask.IsCanceled: False ConnTask.IsFaulted: False
[11:50:31 INF] MainThread: Awaiting connTask result now
[11:52:26 INF] MqttClient: Warning Timeout while waiting for response packet (MqttConnAckPacket).
[11:52:26 INF] MqttClient: Error Error while connecting with server.
MQTTnet.Adapter.MqttConnectingFailedException: Error while authenticating. Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException was thrown.
 ---> MQTTnet.Exceptions.MqttCommunicationTimedOutException: Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException was thrown.
   at MQTTnet.PacketDispatcher.MqttPacketAwaitable1.WaitOneAsync(TimeSpan timeout)
   at MQTTnet.Client.MqttClient.SendAndReceiveAsync[TResponsePacket](MqttBasePacket requestPacket, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.AuthenticateAsync(IMqttChannelAdapter channelAdapter, MqttApplicationMessage willApplicationMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MQTTnet.Client.MqttClient.AuthenticateAsync(IMqttChannelAdapter channelAdapter, MqttApplicationMessage willApplicationMessage, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
[11:52:26 ERR] Establishing Trust failed.
[11:52:29 INF] Attempting to activate
[11:52:29 INF] MainThread: Sending Activation Token to Broker to establish trust.
[11:52:29 INF] MqttClient: Verbose Trying to connect with server 'REDACTED' (Timeout=00:02:00).
[11:52:29 INF] MainThread: ConnTask.Status: WaitingForActivation ConnTask.IsCanceled: False ConnTask.IsFaulted: False
[11:52:29 INF] MqttClient: Verbose Connection with server established.
[11:52:29 INF] MqttClient: Verbose Start receiving packets.
[11:52:29 INF] MqttClient: Verbose Disconnecting [Timeout=00:02:00]
[11:52:29 INF] MqttClient: Verbose Disconnected from adapter.
[11:52:29 INF] MqttClient: Info Disconnected.
[11:52:29 INF] MqttClient: Verbose Stopped receiving packets.
[11:52:29 ERR] DisconnectHandler: Broker Disconnected. Reason: UnspecifiedError Exception:
[11:52:29 INF] DisconnectHandler: ConnectAsync() Task has been requested to cancel: CancelTokenSource.IsCancellationRequested:True
[11:52:30 INF] MainThread: ConnTask.Status: WaitingForActivation ConnTask.IsCanceled: False ConnTask.IsFaulted: False
[11:52:31 INF] MainThread: ConnTask.Status: WaitingForActivation ConnTask.IsCanceled: False ConnTask.IsFaulted: False
[11:52:32 INF] MainThread: ConnTask.Status: WaitingForActivation ConnTask.IsCanceled: False ConnTask.IsFaulted: False
[11:52:33 INF] MainThread: ConnTask.Status: WaitingForActivation ConnTask.IsCanceled: False ConnTask.IsFaulted: False
[11:52:34 INF] MainThread: Awaiting connTask result now
[11:54:29 INF] MqttClient: Warning Timeout while waiting for response packet (MqttConnAckPacket).
[11:54:29 INF] MqttClient: Error Error while connecting with server.
MQTTnet.Adapter.MqttConnectingFailedException: Error while authenticating. Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.
 ---> MQTTnet.Exceptions.MqttCommunicationTimedOutException: Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.
   at MQTTnet.PacketDispatcher.MqttPacketAwaitable1.WaitOneAsync(TimeSpan timeout)
   at MQTTnet.Client.MqttClient.SendAndReceiveAsync[TResponsePacket](MqttBasePacket requestPacket, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.AuthenticateAsync(IMqttChannelAdapter channelAdapter, MqttApplicationMessage willApplicationMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MQTTnet.Client.MqttClient.AuthenticateAsync(IMqttChannelAdapter channelAdapter, MqttApplicationMessage willApplicationMessage, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
[11:54:29 ERR] Establishing Trust failed.
[11:54:32 INF] Attempting to activate
[11:54:32 INF] MainThread: Sending Activation Token to Broker to establish trust.
[11:54:32 INF] MqttClient: Verbose Trying to connect with server 'REDACTED' (Timeout=00:02:00).
[11:54:32 INF] MainThread: ConnTask.Status: WaitingForActivation ConnTask.IsCanceled: False ConnTask.IsFaulted: False
[11:54:33 INF] MqttClient: Verbose Connection with server established.
[11:54:33 INF] MqttClient: Verbose Start receiving packets.
[11:54:33 INF] MqttClient: Verbose Authenticated MQTT connection with server established.
[11:54:33 INF] MqttClient: Info Connected.
[11:54:33 INF] ConnectedHandler: Broker Connection established. Success
[11:54:33 INF] MqttClient: Verbose Start sending keep alive packets.
[11:54:33 INF] MainThread: Awaiting connTask result now
[11:54:40 INF] Activation: SUCCESS!
[11:54:40 INF] MqttClient: Verbose Stopped sending keep alive packets.
[11:54:40 INF] MqttClient: Verbose Disconnecting [Timeout=00:02:00]
[11:54:40 INF] MqttClient: Verbose Disconnected from adapter.
[11:54:40 INF] MqttClient: Verbose Stopped receiving packets.
[11:54:40 INF] MqttClient: Info Disconnected.
[11:54:40 ERR] DisconnectHandler: Broker Disconnected. Reason: NormalDisconnection Exception:

**Comment by chkr1011** [comment]
Please try with version 4 from MyGet feed. A lot of APIs have changed including async method calls and internal thread management.

**Comment by chkr1011** [comment]
Closing this due to inactivity.
