### ISSUE TITLE
Protocol Version 132 (MQTT 3.1.1 Bridge) Support

### ISSUE THREAD

**Issue by mac866** [dotnet/MQTTnet#1413]
Hi,

I currently use MQTTnet as a endpoint for various MQTT clients.
For this reason, I would like to thank you for your great work!

I need to integrate a new "BlackBox-Hardware client", but it connects with protocol version 132 [MQTT 3.1.1 Bridge] which results in:
 
```csharp
MQTTnet.Exceptions.MqttProtocolViolationException: Protocol level '132' not supported.
   at MQTTnet.Formatter.MqttPacketFormatterAdapter.ParseProtocolVersion(ReceivedMqttPacket receivedMqttPacket)
   at MQTTnet.Formatter.MqttPacketFormatterAdapter.DetectProtocolVersion(ReceivedMqttPacket receivedMqttPacket)
   at MQTTnet.Adapter.MqttChannelAdapter.ReceivePacketAsync(CancellationToken cancellationToken)
   at MQTTnet.Server.Internal.MqttClientSessionsManager.ReceiveConnectPacket(IMqttChannelAdapter channelAdapter, CancellationToken cancellationToken)
   at MQTTnet.Server.Internal.MqttClientSessionsManager.HandleClientConnectionAsync(IMqttChannelAdapter channelAdapter, CancellationToken cancellationToken)
```

I cannot change the configuration of this client, but I could reproduce the same behaviour via the Mosquitto Broker in bridge mode.

Are there ways to connect with version 132 without making changes to the client?

THX

**Comment by chkr1011** [comment]
Do you have a link for me with the full protocol specification or more details? Currently there is no way to make a connection but I can add support for this when you provide more details about this feature.

**Comment by chkr1011** [comment]
Please try this version from the myget feed: https://www.myget.org/feed/mqttnet/package/nuget/MQTTnet/4.0.0.180

It allows sending the flag in the client and the server will now "ignore" it so that a connection can be established.

**Comment by SeppPenner** [comment]
Nice, so we can close this issue? :)

**Comment by mac866** [comment]
Yes - THX!
