### ISSUE TITLE
ManagedMqttClient: Unable to subscribe more than 16 topics

### ISSUE THREAD

**Issue by janpalas** [dotnet/MQTTnet#1427]
It is impossible to subscribe more than 16 topics using `ManagedMqttClient`. Connection keeps getting disconnected with this message: ` The remote party closed the WebSocket connection without completing the close handshake.` Interestingly, it is possible to subscribe more than 16 topics without any problems omitting `ManagedMqttClient` and using simple `MqttClient`.

I observed this behavior with MQTTnet.Extensions.ManagedClient NuGet package version `3.1.2` and `4.0.0.167`. Both versions were tested on .NET Core 3.1 and .NET 6 with no difference in behavior.

Configuration of my `ManagedMqttClient`:
```
var clientOptions = new MqttClientOptionsBuilder()
	.WithClientId("kmlk473la")
	.WithWebSocketServer("some.mqtt.server.com")
	.WithTls(new MqttClientOptionsBuilderTlsParameters
	{
		UseTls = true,
		SslProtocol = System.Security.Authentication.SslProtocols.Tls12
	})
	.WithProtocolVersion(MqttProtocolVersion.V500)
	.WithKeepAlivePeriod(TimeSpan.FromMinutes(3))
	.WithCleanSession()
	.Build();

var options = new ManagedMqttClientOptionsBuilder()
	.WithAutoReconnectDelay(TimeSpan.FromSeconds(5))
	.WithClientOptions(clientOptions)
	.Build();

var mqttFactory = new MqttFactory();
var managedMqttClient= mqttFactory.CreateManagedMqttClient();
```

Subscription to topics can be made either by 
```
await managedMqttClient.SubscribeAsync("someTopic/1");
await managedMqttClient.SubscribeAsync("someTopic/2")
...
``` 
or by
```
await managedMqttClient.SubscribeAsync(new List<MqttTopicFilter>
{ 
    new MqttTopicFilter { Topic = "someTopic/1"},
    new MqttTopicFilter { Topic = "someTopic/2"},
    ...
});
```
with no difference in behavior. Everything is working fine when subscribing up to 16 topics. However, when I try to subscribe to 17, 18 or even more topics, connection gets disconnected, ie. disconnected event handler is called with the following exception: `MQTTnet.Exceptions.MqttCommunicationException: The remote party closed the WebSocket connection without completing the close handshake.`

However, when I omit `ManagedMqttClient` and use just `MqttClient` with the same connection options, I can subscribe to any number of topics I want and everything is working without any problem.

**Comment by chkr1011** [comment]
I created a branch for this ticket (see 1427-managedmqttclient-unable-to-subscribe-more-than-16-topics) and added a Unit Test "Subscribe_Lots_Of_Topics" but it seems to work properly. I tried to get a sample very close to you explanation but it simply works. Please have a look and let me know which bits I am missing. The only difference for not is that I am not using a WebSocket connection and TLS.

**Comment by chkr1011** [comment]
Closing this due to inactivity.

**Comment by hsakoh** [comment]
I encountered a similar issue, so I’m recording it here.

I’m connecting to AWS IoT Core using a client certificate. When I attempt to subscribe to 9 topics at once, the connection is disconnected, and it enters an infinite loop.

- Example code:
```csharp
await mqttClient.SubscribeAsync([
    new MqttTopicFilter(){Topic = "topic1/#"},
    new MqttTopicFilter(){Topic = "topic2/#"},
    new MqttTopicFilter(){Topic = "topic3/#"},
    new MqttTopicFilter(){Topic = "topic4/#"},
    new MqttTopicFilter(){Topic = "topic5/#"},
    new MqttTopicFilter(){Topic = "topic6/#"},
    new MqttTopicFilter(){Topic = "topic7/#"},
    new MqttTopicFilter(){Topic = "topic8/#"},
    new MqttTopicFilter(){Topic = "topic9/#"},
]);
```

- Log output:
```
Verbose,ManagedMqttClient,Publishing {0} added and {1} removed subscriptions,9,0,
Verbose,MqttChannelAdapter,TX ({0} bytes) >>> {1},327,Subscribe: [PacketIdentifier=1] [TopicFilters=topic1/#@AtMostOnce,topic2/#@AtMostOnce,topic3/#@AtMostOnce,topic4/#@AtMostOnce,topic5/#@AtMostOnce,topic6/#@AtMostOnce,topic7/#@AtMostOnce,topic8/#@AtMostOnce,topic9/#@AtMostOnce],
Verbose,MqttClient,Disconnecting [Timeout={0}],00:01:40,
Verbose,MqttClient,Disconnected from adapter.,,
Verbose,MqttClient,Stopped sending keep alive packets,,
Info,MqttClient,Disconnected.,,
Verbose,MqttClient,Stopped receiving packets,,
Warning,ManagedMqttClient,Synchronizing subscriptions failed.,,MQTTnet.Client.MqttClientDisconnectedException: The MQTT client is disconnected.
   at MQTTnet.PacketDispatcher.MqttPacketAwaitable`1.WaitOneAsync(CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.Request[TResponsePacket](MqttPacket requestPacket, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.SubscribeAsync(MqttClientSubscribeOptions options, CancellationToken cancellationToken)
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.SendSubscribeUnsubscribe(List`1 addedSubscriptions, List`1 removedSubscriptions, CancellationToken cancellationToken)
Verbose,MqttClient,Trying to connect with server '{0}',Unspecified/xxxxxxxxxxxx-ats.iot.ap-northeast-1.amazonaws.com:8883,
Verbose,MqttClient,Connection with server established,,
Verbose,MqttChannelAdapter,TX ({0} bytes) >>> {1},46,Connect: [ClientId=dbf0011e03da4071b1fb6f44b75435f9] [Username=] [Password=] [KeepAlivePeriod=300] [CleanSession=True],
Verbose,MqttChannelAdapter,RX ({0} bytes) <<< {1},4,ConnAck: [ReturnCode=ConnectionAccepted] [ReasonCode=Success] [IsSessionPresent=False],
Verbose,MqttClient,Authenticated MQTT connection with server established.,,
Verbose,MqttClient,Start receiving packets,,
Info,MqttClient,Connected,,
Verbose,MqttClient,Start sending keep alive packets,,
Info,ManagedMqttClient,Publishing subscriptions at reconnect,,
---
Verbose,MqttChannelAdapter,TX ({0} bytes) >>> {1},327,Subscribe: [PacketIdentifier=1] [TopicFilters=topic1/#@AtMostOnce,topic2/#@AtMostOnce,topic3/#@AtMostOnce,topic4/#@AtMostOnce,topic5/#@AtMostOnce,topic6/#@AtMostOnce,topic7/#@AtMostOnce,topic8/#@AtMostOnce,topic9/#@AtMostOnce],
Verbose,MqttClient,Disconnecting [Timeout={0}],00:01:40,
Verbose,MqttClient,Disconnected from adapter.,,
Verbose,MqttClient,Stopped sending keep alive packets,,
Info,MqttClient,Disconnected.,,
Verbose,MqttClient,Stopped receiving packets,,
Warning,ManagedMqttClient,Synchronizing subscriptions failed.,,MQTTnet.Client.MqttClientDisconnectedException: The MQTT client is disconnected.
   at MQTTnet.PacketDispatcher.MqttPacketAwaitable`1.WaitOneAsync(CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.Request[TResponsePacket](MqttPacket requestPacket, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.SubscribeAsync(MqttClientSubscribeOptions options, CancellationToken cancellationToken)
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.SendSubscribeUnsubscribe(List`1 addedSubscriptions, List`1 removedSubscriptions, CancellationToken cancellationToken)
Verbose,ManagedMqttClient,Stopped publishing messages.,,
Verbose,MqttClient,Trying to connect with server '{0}',Unspecified/xxxxxxxxxxxx-ats.iot.ap-northeast-1.amazonaws.com:8883,
Verbose,ManagedMqttClient,Stopped publishing messages.,,
Verbose,MqttClient,Connection with server established,,
Verbose,MqttChannelAdapter,TX ({0} bytes) >>> {1},46,Connect: [ClientId=dbf0011e03da4071b1fb6f44b75435f9] [Username=] [Password=] [KeepAlivePeriod=300] [CleanSession=True],
Verbose,MqttChannelAdapter,RX ({0} bytes) <<< {1},4,ConnAck: [ReturnCode=ConnectionAccepted] [ReasonCode=Success] [IsSessionPresent=False],
Verbose,MqttClient,Authenticated MQTT connection with server established.,,
Info,MqttClient,Connected,,
Verbose,MqttClient,Start receiving packets,,
Verbose,MqttClient,Start sending keep alive packets,,
Info,ManagedMqttClient,Publishing subscriptions at reconnect,,
---
Infinite loop!!!
```

The cause was due to the limitation of [AWS IoT Core's "Maximum subscriptions per subscribe request"](https://docs.aws.amazon.com/general/latest/gr/iot-core.html#message-broker-limits) (up to 8 topics per subscription request).

As a solution, I divided the topics into every 8 and repeated the subscription process, which worked well.
- Example code:
```csharp
string[] topics = [
    "topic1/#",
    "topic2/#",
    "topic3/#",
    "topic4/#",
    "topic5/#",
    "topic6/#",
    "topic7/#",
    "topic8/#",
    "topic9/#",
];
for (int i = 0; i < topics.Length; i += 8)
{
    await mqttClient.SubscribeAsync(
        topics.Skip(i).Take(8).Select(topic => new MqttTopicFilter() { Topic = topic }).ToArray());
    await Task.Delay(1000);
}
```

I see two main problems:
- The disconnection and subsequent infinite retry loop.
- Even when I call the subscribe method for every 8 topics, if I don’t allow enough time between each subscription, it tries to subscribe to all of them at once. I am dissatisfied with the inability to confirm and wait for the subscription request to be sent. I couldn't resolve this using the PendingApplicationMessagesCount.
