### ISSUE TITLE
Object Disposed Exception in unit test Handle_Parallel_Connection_Attempts

### ISSUE THREAD

**Issue by logicaloud** [dotnet/MQTTnet#1595]
### Describe the bug
When running unit tests, I can fairly regularly produce an error in unit test `Handle_Parallel_Connection_Attempts`, although it works some times. Increasing the number of threads in the test may help produce the error.

It looks like the 'old' client is able to enter the `RunAsync` loop while already taken over. The `IsTakenOver` flag is set when creating the new client in `MqttClientSessionManager`, but there is no synchronization with the client. It may also be possible that the `RunAsync` cancellation token is not yet created when the old client is stopped in `MqttClientSessionManager.CreateClientConnection`, which could be part of the issue. 

If the `oldSession` is not disposed at the end of `MqttClientSessionManager.CreateClientConnection` then there is no error, but that in itself is not a solution.

### Which component is your bug related to?

- Server

### To Reproduce
Run unit test `Handle_Parallel_Connection_Attempts`.

### Expected behavior
The unit test should pass without error.

### Additional context / logging
The error reported is:

```batch
    Test method MQTTnet.Tests.Server.Session_Tests.Handle_Parallel_Connection_Attempts threw exception: 
System.Exception: Server had 6 errors ($[2022-11-28T21:11:23.4913800Z] [server] [49] [MqttClient] [Error]: Client 'Handle_Parallel_Connection_Attempts_1': Error while receiving client packets.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'AsyncLock'.
   at MQTTnet.Internal.AsyncLock.EnterAsync(CancellationToken cancellationToken) in /_/Source/MQTTnet/Internal/AsyncLock.cs:line 48
   at MQTTnet.Server.MqttClientSubscriptionsManager.CreateSubscription(MqttTopicFilter topicFilter, UInt32 subscriptionIdentifier, MqttSubscribeReasonCode reasonCode) in /_/Source/MQTTnet/Server/Internal/MqttClientSubscriptionsManager.cs:line 340
   at MQTTnet.Server.MqttClientSubscriptionsManager.Subscribe(MqttSubscribePacket subscribePacket, CancellationToken cancellationToken) in /_/Source/MQTTnet/Server/Internal/MqttClientSubscriptionsManager.cs:line 197
   at MQTTnet.Server.MqttClient.HandleIncomingSubscribePacket(MqttSubscribePacket subscribePacket, CancellationToken cancellationToken) in /_/Source/MQTTnet/Server/Internal/MqttClient.cs:line 291
   at MQTTnet.Server.MqttClient.ReceivePackagesLoop(CancellationToken cancellationToken) in /_/Source/MQTTnet/Server/Internal/MqttClient.cs:line 442
```

**Comment by chkr1011** [comment]
I attached a branch to this ticket. Please pull it and let me know if it works. In my cases the test was now green every time.

**Comment by logicaloud** [comment]
I can still re-produce the error. Maybe my environment lets me produce the error more easily. I'll have a look over the coming days to see if I can find anything on my side.
