### ISSUE TITLE
Every 100 seconds "The remote party closed the WebSocket connection without completing the close handshake."

### ISSUE THREAD

**Issue by stefxx** [dotnet/MQTTnet#1691]
### Describe the bug
After successfully connecting to a MQTT broker using WebSocket, the connection is disconnected with error "The remote party closed the WebSocket connection without completing the close handshake".
Using ".WithKeepAlivePeriod" does not make any difference. It even happens if messages are being exchanged between broker and client in this time.

### Which component is your bug related to?
- Client

### To Reproduce
Connect to a MQTT broker using WebSocket.
Wait 100 seconds.

### Expected behavior
A way to configure the KeepAlive and/or implement some kind of WebSocket "ping" to keep the session alive

### Additional context / logging
The KeepAlive can be extended by setting ServicePointManager.MaxServicePointIdleTime. But even setting it to Timeout.Infinite it still happens every 15 minutes.

Thanks!

**Comment by stefxx** [comment]
Here is the tracelog:

```
2023-03-12 18:07:09 >> [12-3-2023 17:07:09] [6] [MqttClient] [Verbose]: Trying to connect with server 'iot.eu-west-1.xx-redacted-xx.com'.
2023-03-12 18:07:10 >> [12-3-2023 17:07:10] [8] [MqttClient] [Verbose]: Connection with server established.
2023-03-12 18:07:10 >> [12-3-2023 17:07:10] [10] [MqttClient] [Verbose]: Start receiving packets.
2023-03-12 18:07:10 >> [12-3-2023 17:07:10] [8] [MqttChannelAdapter] [Verbose]: TX (69 bytes) >>> Connect: [ClientId=xx-redacted-xx] [Username=] [Password=] [KeepAlivePeriod=15] [CleanSession=True]
2023-03-12 18:07:10 >> [12-3-2023 17:07:10] [8] [MqttChannelAdapter] [Verbose]: RX (4 bytes) <<< ConnAck: [ReturnCode=ConnectionAccepted] [ReasonCode=Success] [IsSessionPresent=False]
2023-03-12 18:07:10 >> [12-3-2023 17:07:10] [9] [MqttClient] [Verbose]: Authenticated MQTT connection with server established.
2023-03-12 18:07:10 >> [12-3-2023 17:07:10] [9] [MqttClient] [Info]: Connected.
2023-03-12 18:07:10 >> [12-3-2023 17:07:10] [13] [MqttClient] [Verbose]: Start sending keep alive packets.
2023-03-12 18:07:10 >> [12-3-2023 17:07:10] [6] [MqttChannelAdapter] [Verbose]: TX (36 bytes) >>> Subscribe: [PacketIdentifier=1] [TopicFilters=xx-redacted-xx/xx-redacted-xx/commandOut@AtMostOnce]
2023-03-12 18:07:10 >> [12-3-2023 17:07:10] [11] [MqttChannelAdapter] [Verbose]: RX (5 bytes) <<< SubAck: [PacketIdentifier=1] [ReasonCode=GrantedQoS0]
2023-03-12 18:07:25 >> [12-3-2023 17:07:25] [9] [MqttChannelAdapter] [Verbose]: TX (2 bytes) >>> PingReq
2023-03-12 18:07:25 >> [12-3-2023 17:07:25] [8] [MqttChannelAdapter] [Verbose]: RX (2 bytes) <<< PingResp
2023-03-12 18:07:40 >> [12-3-2023 17:07:40] [9] [MqttChannelAdapter] [Verbose]: TX (2 bytes) >>> PingReq
2023-03-12 18:07:40 >> [12-3-2023 17:07:40] [8] [MqttChannelAdapter] [Verbose]: RX (2 bytes) <<< PingResp
2023-03-12 18:07:50 >> [12-3-2023 17:07:50] [16] [MqttChannelAdapter] [Verbose]: RX (501 bytes) <<< Publish: [Topic=xx-redacted-xx/xx-redacted-xx/commandOut] [Payload.Length=468] [QoSLevel=AtMostOnce] [Dup=False] [Retain=False] [PacketIdentifier=0]
2023-03-12 18:07:55 >> [12-3-2023 17:07:55] [10] [MqttChannelAdapter] [Verbose]: TX (2 bytes) >>> PingReq
2023-03-12 18:07:55 >> [12-3-2023 17:07:55] [8] [MqttChannelAdapter] [Verbose]: RX (2 bytes) <<< PingResp
2023-03-12 18:08:10 >> [12-3-2023 17:08:10] [9] [MqttChannelAdapter] [Verbose]: TX (2 bytes) >>> PingReq
2023-03-12 18:08:10 >> [12-3-2023 17:08:10] [8] [MqttChannelAdapter] [Verbose]: RX (2 bytes) <<< PingResp
2023-03-12 18:08:25 >> [12-3-2023 17:08:25] [9] [MqttChannelAdapter] [Verbose]: TX (2 bytes) >>> PingReq
2023-03-12 18:08:25 >> [12-3-2023 17:08:25] [8] [MqttChannelAdapter] [Verbose]: RX (2 bytes) <<< PingResp
2023-03-12 18:08:41 >> [12-3-2023 17:08:41] [9] [MqttChannelAdapter] [Verbose]: TX (2 bytes) >>> PingReq
2023-03-12 18:08:41 >> [12-3-2023 17:08:41] [8] [MqttChannelAdapter] [Verbose]: RX (2 bytes) <<< PingResp
2023-03-12 18:08:50 >> [12-3-2023 17:08:50] [12] [MqttClient] [Warning]: Communication error while receiving packets.
MQTTnet.Exceptions.MqttCommunicationException: The remote party closed the WebSocket connection without completing the close handshake. ---> System.Net.WebSockets.WebSocketException: The remote party closed the WebSocket connection without completing the close handshake. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
   at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslState.get_SecureStream()
   at System.Net.TlsStream.EndRead(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketConnectionStream.<ReadAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
   --- End of inner exception stack trace ---
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Implementations.MqttWebSocketChannel.<ReadAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Adapter.MqttChannelAdapter.<ReadFixedHeaderAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Adapter.MqttChannelAdapter.<ReceiveAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Adapter.MqttChannelAdapter.<ReceivePacketAsync>d__30.MoveNext()
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.WrapAndThrowException(Exception exception)
   at MQTTnet.Adapter.MqttChannelAdapter.<ReceivePacketAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<TryReceivePacketsAsync>d__78.MoveNext()
2023-03-12 18:08:50 >> [12-3-2023 17:08:50] [12] [MqttClient] [Verbose]: Stopped sending keep alive packets.
2023-03-12 18:08:50 >> [12-3-2023 17:08:50] [12] [MqttClient] [Verbose]: Disconnecting [Timeout=00:01:40]
2023-03-12 18:08:50 >> [12-3-2023 17:08:50] [12] [MqttClient] [Verbose]: Disconnected from adapter.
2023-03-12 18:08:50 >> [12-3-2023 17:08:50] [12] [MqttClient] [Info]: Disconnected.
2023-03-12 18:08:50 >> [12-3-2023 17:08:50] [12] [MqttClient] [Verbose]: Stopped receiving packets.

```

**Comment by logicaloud** [comment]
I have tried with the Mosquitto test broker, WebSocket connection to `test.mosquitto.org:8080`, subscribing to topic `$SYS/broker/uptime`. I could not re-produce the problem (still going after 60 minutes). My version may be slightly different from yours though.

Can you re-produce the problem with Mosquitto on your side?

**Comment by stefxx** [comment]
I am using a client API on AWS. I have no control over it. Happy to test with mosquitto broker later today, but even if that works it doesn't really help me.

Is there a way to configure a KeepAlive on the WebSocket socket? It seems like the KeepAlive on the connection is only valid for the MQTT session.

**Comment by stefxx** [comment]
> Can you re-produce the problem with Mosquitto on your side?

I cannot reproduce the issue on the test.mosquitto.org server. So it seems it is specific for an AWS WebSocket connection.

**Comment by logicaloud** [comment]
I'm not sure if the missing WebSocket Ping/Pong should cause an issue and haven't found any definite answer in the AWS docs.

I did come across this doc (https://docs.aws.amazon.com/iot/latest/developerguide/life-cycle-events.html#connect-disconnect) where a second MQTT client subscribing to `$aws/events/presence/disconnected/clientId` could give you a reason as to why AWS has disconnected the other client. Not sure if it helps but it looks like a quick test that can provide another clue?

Also interesting, the listed "Connection duration limits" here: https://docs.aws.amazon.com/iot/latest/developerguide/protocols.html

**Comment by stefxx** [comment]
I try to connect to any flavor of "$aws/events/presence/" including the ClientID, but I get a disconnect every time I try.

**Comment by logicaloud** [comment]
I'll try to re-produce the problem. - Can you confirm that you use a custom authentication lambda? What are your `disconnectAfterInSeconds` and `refreshAfterInSeconds` settings?

**Comment by stefxx** [comment]
Here is my (simplified) test code:

```
Dim TlsParameters As New MqttClientOptionsBuilderTlsParameters() With {
    .SslProtocol = SslProtocols.Tls12,
    .UseTls = True
}
Dim mqttFactory = New MqttFactory()

Using mqttClient = mqttFactory.CreateMqttClient()
    Dim ClientWebSocketOptions As New MqttClientOptionsBuilderWebSocketParameters
    ClientWebSocketOptions.RequestHeaders = New Dictionary(Of String, String) From {
		{"jwt", Token},
		{"x-amz-customauthorizer-signature", Signature}
    }
    Dim ClientOptions As New MqttClientOptionsBuilder()
    ClientOptions.WithClientId("XX/USER/" & UserId & "/XXX/ & Guid)
    ClientOptions.WithWebSocketServer(MqttEndpoint, ClientWebSocketOptions)
    ClientOptions.WithTls(TlsParameters)
    Dim MqttResult = mqttClient.ConnectAsync(ClientOptions.Build()).GetAwaiter().GetResult()
    Console.WriteLine("The MQTT client is connected.")
End Using
```

**Comment by logicaloud** [comment]
The problem seems to be occurring with .NET Framework only, not .NET 6.

As a test, I have established a WebSocket connection to AWS IoT Core (without MQTT connect) and then observed whether the WebSocket remained open. On NET 6, the WebSocket remained open, on .NET Framework 4.8, 4,7.2 or 4.6.2, the WebSocket gets disconnected after 100 seconds.

The MQTTNet library already performs keep-alives on the WebSocket every 30 seconds (the default), so that is not the problem. The problem seems to be this: https://stackoverflow.com/questions/40502921/net-websockets-forcibly-closed-despite-keep-alive-and-activity-on-the-connectio

This work-around described in the stackoverflow post didn't work for me for some reason:

```
System.Net.ServicePointManager.MaxServicePointIdleTime = int.MaxValue;
```

This one did (a change in the `MqttWebSocketChannel` class, method `SetupClientWebSocket`, in the MQTTnet library):

```
clientWebSocket.Options.KeepAliveInterval = TimeSpan.Zero;
```

Both workarounds have drawbacks as described in the post and I'm not sure if either would be a good solution. The WebSocket's 'KeepAliveInterval' could possibly be added as a supported option for MQTTnet library users, so that it could be easily adjusted.

**Comment by stefxx** [comment]
Thanks. Yes, I have played with the ServicePointManager.MaxServicePointIdleTime, setting it to Integer.MaxValue or Timeout.Infinite but did not resolve the issue. Setting it to Infinite did make the disconnect change to every 15 minutes, which is already quite an improvement (but far from perfect).

I understand the drawbacks, but for my particular case I do not see any other viable options. I have other measures in place to ensure a reconnect if the connection stalls or fails, so it could be a solution for me.

**Comment by stefxx** [comment]
To test it myself, I just downloaded the source code of MQTTnet and compiled it. I've added the KeepAliveInterval on the WebSocket, in SetupClientWebSocket and made sure it was applied correctly.

The result was unchanged; I still get the disconnect after 100 seconds... Not sure if I did anything wrong or if you've changed anything else as well?

**Comment by logicaloud** [comment]
That's the only change, except for the conditional:

```
#if NET461_OR_GREATER
            clientWebSocket.Options.KeepAliveInterval = TimeSpan.Zero;
#endif
```

The difference may be that I only establish a WebSocket connection, not an MQTT connection, so in my case no additional messages flow.

I could confirm with curl that the AWS response indeed contains `content-length: 0`, which does not seem to be handled in .NET framework.

```
`curl --include \
     --no-buffer \
     --header "Connection: Upgrade" \
     --header "Upgrade: websocket" \
     --header "Host: <yourendpoint>.amazonaws.com:443" \
     --header "Origin: example.com:443" \
     --header "Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==" \
     --header "Sec-WebSocket-Version: 13" \
     --header "Sec-WebSocket-Protocol: mqtt" \
     https://<yourendpoint>.amazonaws.com:443/
```

Response:
```
HTTP/1.1 101 Switching Protocols
content-length: 0
upgrade: websocket
connection: upgrade
sec-websocket-accept: s3pPLMBiTxaQ9kYGzzhZRbK+xOo=
sec-websocket-protocol: mqtt
...
```

It looks like, MQTTnet can't do much about this behavior. Maybe you could replace the `MqttWebSocketChannel` with a different implementation (as a `IMqttChannel`), or move to .NET 6, or add a separate .NET 6 process as the MQTT client with inter-process communication to your .NET framework application?

**Comment by stefxx** [comment]
Thanks for your efforts @logicaloud . I am afraid you are right.

For now, I will stick with a 15 minute reconnect which seems to work OK. Not pretty but it works.

I will close this now. Any chance you can look at my other issue, [disconnect at publish](https://github.com/dotnet/MQTTnet/issues/1690)? I have no way how to troubleshoot that further. Thanks!
