### ISSUE TITLE
I have founded some error while trying to use ApplicationMessageReceivedAsync got me error  Cannot access a disposed context instance.

### ISSUE THREAD

**Issue by panupong-sudj** [dotnet/MQTTnet#1705]
### Describe the bug
when I try to handle My OrderId and Status get from MQTT Broker with 
```
client.ApplicationMessageReceivedAsync += async e =>
            {
                var payload = Encoding.UTF8.GetString(e.ApplicationMessage.Payload);

                try
                {
                    var message = JsonSerializer.Deserialize<Order>(payload);
                    if (message == null)
                    {
                        Console.WriteLine($"Don't Recive any Message");

                    }
                    await ProcessOrderStatusMessageAsync(message.OrderID, message.Status);
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Error deserializing message: {ex.Message}");
                }
            };
```

that call function await ProcessOrderStatusMessageAsync(message.OrderID, message.Status);
```
   public async Task ProcessOrderStatusMessageAsync(int orderId, string status)
        {
            try
            {
                _logger.LogInformation("Starting to process order {OrderId}", orderId);
                //Find the current order
                var currentOrder = await _context.Order.FindAsync(orderId);  // Error cause on this line 

                if (currentOrder == null)
                {
                    Console.WriteLine($"Order not found: {orderId}");
                    return;
                }

                // Check if the status has changed
                if (currentOrder.Status == status)
                {
                    Console.WriteLine($"Status already set to {status}: {orderId}");
                    return;
                }

                // Update the order status
                currentOrder.Status = status;
                _context.Order.Update(currentOrder);
                await _context.SaveChangesAsync();

                // Send notification to clients
                await _orderHub.Clients.All.SendAsync("OrderStatusChanged", orderId, status);
               // Update Order Status
                await UpdateOrderStatusAsync(orderId);

                _logger.LogInformation("Order {OrderId} processed successfully", orderId);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error ProcessOrderStatusMessageAsync: {ex.Message}");
                Console.WriteLine(ex);
            }
        }
```
got this error 
```batch
Error ProcessOrderStatusMessageAsync: Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling 'Dispose' on the context instance, or wrapping it in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'OMCContext'.
System.ObjectDisposedException: Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling 'Dispose' on the context instance, or wrapping it in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'OMCContext'.
   at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Internal.IDbContextDependencies.get_EntityFinderFactory()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_Finder()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.FindAsync(Object[] keyValues)
   at OMC.Pages.waitingOrderModel.ProcessOrderStatusMessageAsync(Int32 orderId, String status) in C:\Project\OMC\Pages\waitingorder.cshtml.cs:line 154
```
I have tried manual call function and it works fine can you help me find out what is happening   

this is my Onget() method that use this fucntion
```
public async Task<IActionResult> OnGetAsync(int id)
        {
          

            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Order.FirstOrDefaultAsync(m => m.OrderID == id);

            if (order == null)
            {
                return NotFound();
            }



            Order = order;
            var previousOrder = await _context.Order
            .OrderByDescending(o => o.OrderID)
            .FirstOrDefaultAsync(o => o.OrderID < id && o.Status != "Done" && o.Status == "onProcess");
            QueuePosition = previousOrder == null ? 0 : (id - previousOrder.OrderID);
            Order.QueuePosition = QueuePosition;
            await Handle_Received_Application_Message();
          
            return Page();
        }
```

**Comment by Jeanot-Zubler** [comment]
somewhere in your application you are calling `_context.Dispose()` or you are implementing a `using var _context` pattern. this results in the context already being disposed in your message processor.

**Comment by panupong-sudj** [comment]
> somewhere in your application you are calling `_context.Dispose()` or you are implementing a `using var _context` pattern. this results in the context already being disposed in your message processor.

I have checked my code and I don't calling _context.Disopse() or using var _context but I found the solution to fixed this error , so thank you appreciate your help
