### ISSUE TITLE
SSL Handshake failed with OpenSSL error

### ISSUE THREAD

**Issue by patolax** [dotnet/MQTTnet#1884]
We are trying to access the out customer mqtt server. They have provided us with a CA certificate, client crt, and key files. 
When we try it with test https://test.mosquitto.org/ setup on Windows following code works ok. But on Linux we get this error.

Any idea how to fix this in .net core? We are using the 4.3.1873 version.

```
mqtt communication error: Authentication failed, see inner exception. --> Authentication failed, see inner exception. --> SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL. --> error:0A000410:SSL routines::sslv3 alert handshake failure MQTTnet.Exceptions.MqttCommunicationException: Authentication failed, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:0A000410:SSL routines::sslv3 alert handshake failure
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync(CancellationToken cancellationToken)
   at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync(CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.WrapAndThrowException(Exception exception)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectInternal(IMqttChannelAdapter channelAdapter, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(MqttClientOptions options, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(MqttClientOptions options, CancellationToken cancellationToken)
```

```

Protected MqttClientOptions CreateMqttClientOptions(string hostname, int port)
    {
        var mqttClientOptionsBuilder = new MqttClientOptionsBuilder()
        .WithTcpServer(hostname, port);

        var mqttCfg = Configuration.GetSection("Mqtt").Get<MqttConfiguration>();

        if (!string.IsNullOrEmpty(mqttCfg.ClientCertificateFilePath) && File.Exists(mqttCfg.ClientCertificateFilePath))
        {
            mqttClientOptionsBuilder.WithTlsOptions(
                o =>
                {
                    o.WithAllowUntrustedCertificates(mqttCfg.AllowUntrustedCertificates);
                    IEnumerable<X509Certificate2> CreateCertificates()
                    {
                        var certificates = new List<X509Certificate2>();
                        if (!string.IsNullOrEmpty(mqttCfg.ClientCertificateFilePassword))
                        {
                            if (File.Exists(mqttCfg.ClientCertificateFilePath))
                            {
                                var certificate = new X509Certificate2(mqttCfg.ClientCertificateFilePath, mqttCfg.ClientCertificateFilePassword,
                                    X509KeyStorageFlags.Exportable);
                                certificates.Add(certificate);
                            }
                            else
                            {
                                Logger.LogWarning($"{mqttCfg.ClientCertificateFilePath} not found");
                            }

                        }
                        if (!string.IsNullOrWhiteSpace(mqttCfg.ClientCertificateKeyFilePath))
                        {
                            if (File.Exists(mqttCfg.ClientCertificateFilePath) && File.Exists(mqttCfg.ClientCertificateKeyFilePath))
                            {
                                var certificate = X509Certificate2.CreateFromPemFile(
                                   mqttCfg.ClientCertificateFilePath,
                                   mqttCfg.ClientCertificateKeyFilePath);

                                using (var certStore = new X509Store(StoreName.My, StoreLocation.CurrentUser))
                                {
                                    certStore.Open(OpenFlags.ReadWrite);
                                    certStore.Add(certificate);
                                }

                                if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
                                {
                                    var certificateExport = new X509Certificate2(certificate.Export(X509ContentType.Pkcs12));
                                    certificates.Add(certificateExport);
                                }
                                else
                                {
                                   // new X509Certificate2(certificate.Export(X509ContentType.Pfx))
                                    certificates.Add(certificate);
                                }
                            }
                            else
                            {
                                Logger.LogWarning($"{mqttCfg.CertificateAuthorityFilePath} or {mqttCfg.ClientCertificateKeyFilePath} not found");
                            }
                        }
                        if (!string.IsNullOrWhiteSpace(mqttCfg.CertificateAuthorityFilePath))
                        {
                            if (File.Exists(mqttCfg.CertificateAuthorityFilePath))
                            {
                                var certificate = new X509Certificate2(mqttCfg.CertificateAuthorityFilePath);
                                certificates.Add(certificate);
                            }
                            else
                            {
                                Logger.LogWarning($"{mqttCfg.CertificateAuthorityFilePath} not found");
                            }

                        }
                        return certificates;
                    }

                    var certificates = CreateCertificates();
                    o.WithClientCertificates(certificates);
                    o.WithIgnoreCertificateChainErrors(mqttCfg.IgnoreCertificateErrors);
                    o.WithIgnoreCertificateRevocationErrors(mqttCfg.IgnoreCertificateErrors);
                    o.WithSslProtocols(SslProtocols.Tls12);
                });
        }

        var mqttClientOptions = mqttClientOptionsBuilder
            .Build();
        return mqttClientOptions;
    }
```

**Comment by marcus-dev** [comment]
Hello @patolax. 
Why did you close this bug ? How did you fix it ?
I am seeing the same problem

**Comment by patolax** [comment]
exact code works in Linux, you have to follow these instructions and create two files client cert files.
https://test.mosquitto.org/ssl/

Then above code should work on both windows and linux

**Comment by marcus-dev** [comment]
Meanwhile; I had it working reversing my CA chain order (had to put the CA after the private cert).

As seen here: https://github.com/dotnet/MQTTnet/issues/1309
I guess this is same issue, you have the CA added at last in the code.

**Comment by patolax** [comment]
yup, my code ads CA cert last.
